/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    CreatePost: typeof import('./src/components/CreatePost.vue')['default']
    EditPostComponent: typeof import('./src/components/EditPostComponent.vue')['default']
    Loader: typeof import('./src/components/Loader.vue')['default']
    Login: typeof import('./src/components/Login.vue')['default']
    Navbar: typeof import('./src/components/Navbar.vue')['default']
    NewsCard: typeof import('./src/components/news/NewsCard.vue')['default']
    NewsDetail: typeof import('./src/components/news/NewsDetail.vue')['default']
    Register: typeof import('./src/components/Register.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ValidationError: typeof import('./src/components/ValidationError.vue')['default']
  }
}
