export { default as HomeView } from './HomeView.vue'
export { default as RegisterView } from './RegisterView.vue'
export { default as LoginView } from './LoginView.vue'
export { default as ArticleDetailsView } from './ArticleDetailsView.vue'
export { default as CreatePostView } from './CreatePostView.vue'
export { default as EditPostView } from './EditPostView.vue'